name: Build Pull Requests

on:
- pull_request

jobs:
  snapcraft-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
        - linux/amd64
        - linux/386
        - linux/arm64
        - linux/arm/v7
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      id: build
      run: |
        sudo systemctl restart docker
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm --tty --privileged \
          --volume "$GITHUB_WORKSPACE":"$GITHUB_WORKSPACE" \
          --workdir "$GITHUB_WORKSPACE" \
          --platform "${{ matrix.architecture }}" \
          diddledan/snapcraft:core snap run snapcraft

          SNAPFILE="$(find "$GITHUB_WORKSPACE" -maxdepth 1 -type f -name "*.snap" | head -n1 | sed -Ee "s|^$GITHUB_WORKSPACE/?||")"
          sudo chown "$(id -u)":"$(id -g)" "$SNAPFILE"
          echo ::set-output name=snap::"$SNAPFILE"
    - name: Review
      uses: diddlesnaps/snapcraft-review-tools-action@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        isClassic: 'true'
    - name: Save snap
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.build.outputs.snap }}
        path: ${{ steps.build.outputs.snap }}
