name: Build Pull Requests

on:
- pull_request

jobs:
  snapcraft-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
        - amd64
        - i386
        - arm64
        - armhf
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt@sha256:df15403e06a03c2f461c1f7938b171fda34a5849eb63a70e2a2109ed5a778bde
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: build
      with:
        architecture: ${{ matrix.architecture }}
    - name: Review
      uses: diddlesnaps/snapcraft-review-tools-action@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        isClassic: 'true'
    - name: Save snap
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.architecture }}.snap
        path: ${{ steps.build.outputs.snap }}
